# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webcore', '0027_auto_20170902_1618')
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcore.Profile')),
            ],
            options={
                'verbose_name': 'Feedback',
            },
        ),
    ]
