# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-25 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_contact',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
