# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-01 10:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webcore', '0043_merge_20171015_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('meet_up', models.CharField(choices=[('NO', 'NO'), ('ONLINE', 'ONLINE'), ('IN_PERSON', 'IN PERSON')], max_length=100)),
                ('rate_f50', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('anymore_feedback', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcore.Profile')),
            ],
        ),
    ]
