# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 02:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0027_auto_20170901_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='degree_programme_2',
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree_major',
            field=models.CharField(choices=[('MAJOR1', 'MAJOR1'), ('MAJOR2', 'MAJOR2'), ('MAJOR3', 'MAJOR3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree_programme',
            field=models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Engineering', 'Engineering'), ('Mathematics', 'Mathematics')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Rather not say', 'Rather not say')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2017)]),
        ),
    ]
