# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0027_auto_20170902_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xpairs',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='xpairs',
            name='mentor',
        ),
        migrations.DeleteModel(
            name='Xpairs',
        ),
    ]
