# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 23:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0028_auto_20170930_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mentee_number_remaning',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='paired_with2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='paired_with3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
