# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0029_auto_20171006_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='paired_with',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='paired_with2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='paired_with3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
