# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0030_auto_20170930_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='medium_interaction',
            field=models.CharField(choices=[('Online', 'Online'), ('In person', 'In person'), ('Both', 'Both')], max_length=50, null=True),
        ),
    ]
