# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0032_auto_20170930_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree_major',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
