# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0031_auto_20171006_1138'),
        ('webcore', '0038_auto_20171006_0951'),
    ]

    operations = [
    ]
