# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0039_merge_20171012_1528'),
        ('webcore', '0040_auto_20171012_1413'),
    ]

    operations = [
    ]
