# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0040_auto_20171015_1230'),
        ('webcore', '0041_merge_20171012_1747'),
    ]

    operations = [
    ]
