# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-15 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0042_merge_20171015_1336'),
        ('webcore', '0040_auto_20171012_1757'),
    ]

    operations = [
    ]
