# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0011_pair_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a unique pair name', max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='pair',
            table=None,
        ),
    ]
