# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog_images/stock_photo.jpg', upload_to='blog_images'),
        ),
    ]
