# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170924_1511'),
        ('blog', '0003_auto_20170924_1444'),
    ]

    operations = [
    ]
