# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_20170924_1512'),
        ('blog', '0003_auto_20170924_1511'),
    ]

    operations = [
    ]
