# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_merge_20170924_1536'),
        ('blog', '0005_auto_20170925_1047'),
    ]

    operations = [
    ]
