# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20170813_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('docfile', models.FileField(null=True, upload_to='content_summary/')),
            ],
        ),
        migrations.DeleteModel(
            name='Training',
        ),
        migrations.AddField(
            model_name='mentee',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
