# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20171011_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content_summary',
            name='docfile',
        ),
        migrations.AddField(
            model_name='content_summary',
            name='image',
            field=models.ImageField(default='blog_images/stock_photo.jpg', upload_to='content_summary/images/'),
        ),
        migrations.AddField(
            model_name='mentee',
            name='image',
            field=models.ImageField(default='blog_images/stock_photo.jpg', upload_to='mentee/images/'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='image',
            field=models.ImageField(default='blog_images/stock_photo.jpg', upload_to='mentor/images/'),
        ),
    ]
