# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20171011_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_summary',
            name='title2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
