# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_content_summary_title2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
